name: stillshot
description: A simple, bare-bones static site generator with markdown and mustache templating support.
version: 0.1.3
homepage: https://github.com/oblique63/StillShot
author: Enrique Gavidia <enrique@enriquegavidia.com>

dependencies:
  intl: any
  path: any
  yaml: any
  markdown: any
  mustache: '>= 0.1.7'